##
## LINUX EXAMPLE CONFIG FILE
##

# Key Codes:
# sudo showkey --keycodes
# 
# 125: mod
# 42: shift
# 31: s

[config]
inputPort = 2


## Bottom Row

[[mapping]]
name = "Bottom Left - Terminal"
byte0 = 144
byte1 = 37
type = "command"
command = "kitty"

[[mapping]]
name = "Bottom Middle - File Browser"
byte0 = 144
byte1 = 38
type = "command"
command = "thunar"

[[mapping]]
name = "Bottom Right - Firefox"
byte0 = 144
byte1 = 39
type = "command"
command = "firefox"


## Middle Row

[[mapping]]
name = "Middle Left - Copy Full Number Date"
byte0=144
byte1=42
type="command"
command = "date +%m-%d-%+4Y | wl-copy"

[[mapping]]
name = "Middle Middle - Copy Full Word Date"
byte0=144
byte1=43
type="command"
command = 'date "+%A, %b %d, %+4Y" | wl-copy'

[[mapping]]
name = "Middle Right - Copy 12 Hour Time"
byte0=144
byte1=36
type="command"
command = 'date "+%I:%M %p" | wl-copy'


## Top Row

[[mapping]]
name = "Top Left - Screenshot"
byte0 = 144
byte1 = 47
type = "key"
key = [125, 42, 31]

[[mapping]]
name = "Top Middle - Special Work Space"
byte0 = 144
byte1 = 40
type = "key"
key = [125, 24]

[[mapping]]
name = "Top Right - Open CSUN Canvas"
byte0 = 144
byte1 = 41
type = "command"
command = "firefox --new-tab --url https://canvas.csun.edu/"
